### ISSUE TITLE
Get an error trying to renew (list index out of range)

### ISSUE THREAD

**Issue by simkin** [lukas2511/dehydrated#583]
See the output below, somehow the renewal fails. Would appreciate some input how to fix this

Global API Key (cloudflare)
 ```
+ Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Sep  3 09:21:56 2018 GMT Certificate will expire
(Less than 30 days). Renewing!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for domain.tld
 + 1 pending challenge(s)
 + Deploying challenge tokens...
 + CloudFlare hook executing: deploy_challenge
 + Creating TXT record: domain.tld => ouuWOE1aylFr_vHvPrdQkFVukrXvXTOQpxxxxxxxxx
 + Challenge: mxAGSLEWLXvkVJeG2FKPSLxSKabwTDy-xxxxxxxxx
Traceback (most recent call last):
  File "/opt/dehydrated/hooks/cloudflare/hook.py", line 206, in <module>
    main(sys.argv[1:])
  File "/opt/dehydrated/hooks/cloudflare/hook.py", line 203, in main
    ops[argv[0]](argv[1:])
  File "/opt/dehydrated/hooks/cloudflare/hook.py", line 167, in create_all_txt_records
    create_txt_record(args[i:i+X])
  File "/opt/dehydrated/hooks/cloudflare/hook.py", line 105, in create_txt_record
    zone_id = _get_zone_id(domain)
  File "/opt/dehydrated/hooks/cloudflare/hook.py", line 83, in _get_zone_id
    return r.json()['result'][0]['id']
IndexError: list index out of range
```
Origin CA Key (cloudflare)
```
 + CloudFlare hook executing: startup_hook
Processing *.domain.tld
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Sep  3 09:21:56 2018 GMT Certificate will expire
(Less than 30 days). Renewing!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for domain.tld
 + 1 pending challenge(s)
 + Deploying challenge tokens...
 + CloudFlare hook executing: deploy_challenge
 + Creating TXT record: vault13.eu => ouuWOE1aylFr_vHvPrdQkFVukrXvXTOQp1FJxxxxx
 + Challenge: mxAGSLEWLXvkVJeG2FKPSLxSKabwTDy-M47DWxxxxx
Traceback (most recent call last):
  File "/opt/dehydrated/hooks/cloudflare/hook.py", line 206, in <module>
    main(sys.argv[1:])
  File "/opt/dehydrated/hooks/cloudflare/hook.py", line 203, in main
    ops[argv[0]](argv[1:])
  File "/opt/dehydrated/hooks/cloudflare/hook.py", line 167, in create_all_txt_records
    create_txt_record(args[i:i+X])
  File "/opt/dehydrated/hooks/cloudflare/hook.py", line 105, in create_txt_record
    zone_id = _get_zone_id(domain)
  File "/opt/dehydrated/hooks/cloudflare/hook.py", line 82, in _get_zone_id
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.cloudflare.com/client/v4/zones?name=eu
```

**Comment by pastukhov** [comment]
Looks like cloudflare hook does something wrong.

**Comment by lukas2511** [comment]
This is an issue with your hook-script, not with dehydrated itself.
